version: "3.8"
services:
  db:
    image: postgres:13
    container_name: troca-garrafao-db
    environment:
      POSTGRES_DB: troca-garrafao
      POSTGRES_USER: daviaalves
      POSTGRES_PASSWORD: daviaalves
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: troca-garrafao-api
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://daviaalves:daviaalves@db:5432/troca-garrafao?schema=public"
      NODE_ENV: development
      JWT_SECRET: "odaviamaalivia"

volumes:
  pgdata:
